export const Data = [
  {
    title: 'React-Resturant',
    description: "I'm a beginner to React so this is my first project with react, however I've been using it for quite some time now. I had a lot of fun doing this project and learnt a lot about using React.",
      image: require('./images/1.png'),
      tags: ['React', 'Css',"Tailwind","React"],
    source: 'https://billal2022.github.io/ch1-React-Resturant/',
    visit: 'https://github.com/billal2022/ch1-React-Resturant.git',
    id: 0,
  },
  {
    title: 'Dshboard App',
    description: "I built a React Admin Dashboard App with multiple pages and features, including custom charts calendar and more.",
    image: require('./images/4.png'),
    tags: ['Html','Scss','Css', 'Bootstap'],
    source: 'https://billal2022.github.io/ch1-REACT-DshboardApp/',
    visit: 'https://github.com/billal2022/ch1-REACT-DshboardApp.git',
    id: 1,
  },
  {
    title: 'Space-tourism',
    description: "This project was challenging and fun to do, perfect chance to improve my css skills to a level higher and react too!",
      image: require('./images/3.png'),
      tags: ['Html','Scss','Css', 'React'],
    source: 'https://billal2022.github.io/ch2-react-FEM-Space-tourism/',
    visit: 'https://github.com/billal2022/ch2-react-FEM-Space-tourism.git',
    id: 2,
  },
  {
    title: 'Insure landing page',
    description:" Testing my layout skills with this HTML & CSS only landing page. This challenge is perfect if am starting to get confident in laying out web pages.",
    image: require('./images/2.png'),
    tags: ['Html','Scss','Css', 'Bootstap'],
    source: 'https://billal2022.github.io/ch27-FEM-Insure-landing-page/',
    visit: 'https://github.com/billal2022/ch27-FEM-Insure-landing-page.git',
    id: 3,
  },
]